---

- name: APT | Install sury key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
  become: yes

- name: APT | Add DotDeb stretch repository
  apt_repository: repo="{{ item }}"
  with_items:
    - "deb https://packages.sury.org/php/ stretch main"
  become: yes