- name: update the apt cache
  apt: update_cache=yes

- name: install additional software
  apt: >
    name={{ default_programs }}
    state=present
    update_cache=yes
    cache_valid_time=1

- name: set login dir for vagrant user
  lineinfile:
    path: /home/vagrant/.bashrc
    line: cd /vagrant