---
- name: download sf installer
  get_url:
    url: https://get.symfony.com/cli/installer
    dest: /tmp/symfony3
    mode: '0777'

- name: Execute sf
  command: /bin/bash /tmp/symfony3

- name: Move sf
  command: mv /root/.symfony/bin/symfony /usr/local/bin/symfony

